personal_portfolio_project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:post_id>', views.detail, name='detail')
]

personal_portfolio_project/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views as portfolio_views

urlpatterns = [
    path('', portfolio_views.home, name='portfolio'),
    # path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
<<<<<<< HEAD
    path('fraude/', portfolio_views.fraude, name='fraude'),
    path('agathinha/', portfolio_views.agathinha, name='agathinha'),
=======
    path('fraude/', portfolio_views.fraude, name='fraude')
>>>>>>> 171912b1ad87cf44a656baf5b6edbfb307bc7c67
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio_project/blog/models.py
from django.db import models
from datetime import date

class Post(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateField(default=date.today)
    description = models.TextField()

    def __str__(self):
        return self.title

personal_portfolio_project/portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

personal_portfolio_project/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def home(request):
    posts = Post.objects.order_by('-pub_date')
    return render(request, 'blog/home.html', {'posts': posts})

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/detail.html', {'post': post})

personal_portfolio_project/portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

def fraude(request):
    return render(request, 'portfolio/home.html')
<<<<<<< HEAD

def agathinha(request):
    return render(request, 'portfolio/agathinha.html')
=======
>>>>>>> 171912b1ad87cf44a656baf5b6edbfb307bc7c67

personal_portfolio_project/blog/templates/blog/all_blogs.html
Hello, blog!

personal_portfolio_project/blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container text-center">
  <h1>{{ post.title }}</h1>

  <h2>--{{ post.pub_date|date:'F jS y' }}--</h2>

  {{ post.description|safe }}
</div>
{% endblock %}

personal_portfolio_project/blog/templates/blog/home.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container text-center">
  <h1>Weiglas's Blog</h1>
  <h3>Weiglas has written {{ posts.count }} blog post{{ posts.count|pluralize }}</h3>

  {% for post in posts %}
  <h2><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></h2>
  <h5>{{ post.pub_date|date:'M d y'|upper }}</h5>
  <p>{{ post.description|striptags|truncatechars:100 }}</p>
  {% endfor %}
</div>
{% endblock %}

personal_portfolio_project/portfolio/templates/portfolio/agathinha.html
{% extends 'portfolio/base2.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <p>Não se admire se um dia
Um beija flor invadir
A porta da tua casa
Te der um beijo e partir
Foi eu que mandei o beijo
Que é pra matar meu desejo
Faz tempo que eu não te vejo
Ai que saudade d'ocê</p>
      </div>
    </div>


    <div class="row" id="weiglas-img">
      <img src="{% static 'portfolio/agatha.jpg' %}" alt="Agatha" class="img-fluid">
    </div>


  <!-- <div class="row text-center"> -->
    <!-- {% for project in projects %} -->

      <!-- <div class="col-md-4 col-sm-12"> -->
        <!-- <h2>{{ project.title|truncatechars:20 }}</h2> -->
        <!-- <p>{{ project.description|truncatechars:20 }}</p> -->

        <!-- <img class="img-fluid" src="{{ project.image.url }}" height="250"> -->

        <!-- {% if project.url %} -->
          <!-- <br> -->
          <!-- <a href="{{ project.url }}">Link</a> -->
        <!-- {% endif %} -->

      <!-- </div> -->
    <!-- {% endfor %} -->
  <!-- </div> -->
</div>
{% endblock %}

personal_portfolio_project/portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% block style %}
    {% endblock %}

    <title>FRAUDE</title>
  </head>
  <body>
    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <a class="navbar-brand" href="{% url 'portfolio' %}">Weiglas Ribeiro</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio' %}">Home<span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:home' %}">Blog</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="https://twitter.com/dabliucomsomdeu" target="_blank">Twitter</a>
            </li>
          </ul>
        </div>
      </div>
    </nav> -->

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

personal_portfolio_project/portfolio/templates/portfolio/base2.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% block style %}
    {% endblock %}

    <title>Saudade d'ocê</title>
  </head>
  <body>
    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <a class="navbar-brand" href="{% url 'portfolio' %}">Weiglas Ribeiro</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio' %}">Home<span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:home' %}">Blog</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="https://twitter.com/dabliucomsomdeu" target="_blank">Twitter</a>
            </li>
          </ul>
        </div>
      </div>
    </nav> -->

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

personal_portfolio_project/portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>LINDO</h1>
      </div>
    </div>


    <div class="row" id="weiglas-img">
      <img src="{% static 'portfolio/fraude.jpg' %}" alt="Weiglas hangloosing" class="img-fluid">
    </div>


  <!-- <div class="row text-center"> -->
    <!-- {% for project in projects %} -->

      <!-- <div class="col-md-4 col-sm-12"> -->
        <!-- <h2>{{ project.title|truncatechars:20 }}</h2> -->
        <!-- <p>{{ project.description|truncatechars:20 }}</p> -->

        <!-- <img class="img-fluid" src="{{ project.image.url }}" height="250"> -->

        <!-- {% if project.url %} -->
          <!-- <br> -->
          <!-- <a href="{{ project.url }}">Link</a> -->
        <!-- {% endif %} -->

      <!-- </div> -->
    <!-- {% endfor %} -->
  <!-- </div> -->
</div>
{% endblock %}